# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movies' do
	# Comment the next line if you don't want to use dynamic frameworks
	use_frameworks!
	
	# Pods for Movies
	pod 'SnapKit', '~> 5.0.0'
	
	target 'MoviesTests' do
		inherit! :search_paths
		# Pods for testing
		pod 'SnapKit', '~> 5.0.0'
		
	end
	
end
